.github/workflows/python-app.yml, HQSmokeTests/settings-sample.cfg, HQSmokeTests/testCases/conftest.py, HQSmokeTests/testCases/test_02_users.py, HQSmokeTests/testPages/users/web_user_page.py, HQSmokeTests/userInputs/user_inputs.py
Earlier the invite webuser test case had a couple of missing workflows. This PR deals with the same.
Basically added workflows:
-  to verify invitation mail is sent
- accept web user invitation mail and check if that's successful
However, this fails on CI due to reCaptcha. So, commented the code, but the idea is to push the new code to master and address it later as a part of [QA-4181](https://dimagi-dev.atlassian.net/browse/QA-4181)
=> Missing workflow for web user invitation

HQSmokeTests/settings-sample.cfg
A small change to make the config parameters more understandable for the end user.
=> Added description for config parameters used for HQ tests

HQSmokeTests/testCases/test_06_data.py, HQSmokeTests/testPages/data/reassign_cases_page.py
The Reassign Cases test was failing on Prod env because it was unable to assert the username to which the case was reassigned due to different users were being used on staging & prod. 
Therefore, I have added an if condition to assert accordingly depending on the environment on which the test is running. 
=> Fix for Reassign Cases test failing on Prod

.github/workflows/request_api.yml
- Earlier mails were not being triggered to the QA team, changed that to qa@dimagi.com
- Removed job trigger on push and pull, because it is not likely to fail due to that (unless changes made to it specifically)
=> Updated API Gitaction workflow

.github/workflows/python-app.yml
This should make it easier to see which env a job is running on without having to load the log output.
=> add job name with environment

HQSmokeTests/testPages/data/deduplicate_case_page.py
This PR is for the fix of test_case_58_deduplicate_cases.
The test case was failing on Staging because of the recent changes on the 'Create Deduplication Rule' where Jenny have added a drop down commbox for the case properties in place of a input field. 
Since, this change has not been deployed on Production yet, this test was failing on Staging only. This is now fixed and it is wokring on both the environments.
=> Fixed failure of test_case_58_deduplicate_cases

HQSmokeTests/testPages/android/android_screen.py, HQSmokeTests/testPages/webapps/web_apps_page.py
Fixes for Testcase 15_16 and 38
For testcase 15_16, updated locator of webapps textarea input field
For testcase 38, old apk expired in browserstack so uploaded the apk and updated app_url value in script
=> fix for testcase 15,16 and 38

HQSmokeTests/testPages/data/import_cases_page.py, HQSmokeTests/userInputs/user_inputs.py
Fix for test case 29 reassign cases
After creating the common utilities, a path is changed in the reassign cases. Added that path in HQSmokeTest userData as it was specific to HQSmokeTest and did not add it in the common utilities.
=> fix for testcase_29

HQSmokeTests/testCases/test_09_messaging.py, HQSmokeTests/testPages/messaging/messaging_page.py, HQSmokeTests/testPages/reports/report_page.py, HQSmokeTests/userInputs/user_inputs.py, common_utilities/selenium/base_page.py
Added new workflow for checking conditional alert's messaging history status
The below files have been updated:
- messaging_page.py: updated steps and added new locators related to create_cond_alert()
- base_page.py: added new method for deselect_all options from dropdown
- report_page.py: added new method validate_messaging_history_for_cond_alert()
- test_09_messaging.py: updated steps of test_case_44_create_cond_alert()
- user_inputs.py: added user data related to the changes made.
https://dimagi-dev.atlassian.net/browse/QA-4433
=> added new workflow for checking conditional alert messaging history

.github/workflows/case-search-tests.yml
Added trigger to slack in case search failures
The case search mails were getting lost in the dump of script result emails. This will trigger failures on slack channel #qa-gitactions like:
Here's the app created on slack to configure webhooks: https://api.slack.com/apps/A04HL5CHZMF/incoming-webhooks?success=1
[https://dimagi-dev.atlassian.net/browse/QAV2-4347 ](https://dimagi-dev.atlassian.net/browse/QAV2-4347)
=> Added trigger to slack in case search failures

.github/workflows/case-search-tests.yml, .github/workflows/hq-smoke-tests.yml, .github/workflows/request_api.yml
Trigger Failure Alerts on Slack Channels
- Added slack failure alert triggers for HQ and API on Slack channel #qa-smoke-script-results
- Added slack failure alert triggers for Casesearch on Slack channel #qa-ush-script-results
- Added webhook URLs separately for the both here https://api.slack.com/apps/A04HL5CHZMF/incoming-webhooks?success=1
- Added secrets SLACK_WEBHOOK_URL_USH and SLACK_WEBHOOK_URL_SMOKE for separate triggers
[https://dimagi-dev.atlassian.net/browse/QA-4347](https://dimagi-dev.atlassian.net/browse/QA-4347)
=> Added slack failure alert triggers for HQ and API and updated WEBHOOK URLS

.github/workflows/hq-smoke-tests.yml, .github/workflows/request_api.yml
Trigger Failure Alerts on Slack Channels
- Added slack failure alert triggers for HQ and API on Slack channel #qa-smoke-script-results
- Added slack failure alert triggers for Casesearch on Slack channel #qa-ush-script-results
- Added webhook URLs separately for the both here https://api.slack.com/apps/A04HL5CHZMF/incoming-webhooks?success=1
- Added secrets SLACK_WEBHOOK_URL_USH and SLACK_WEBHOOK_URL_SMOKE for separate triggers
[https://dimagi-dev.atlassian.net/browse/QA-4347](https://dimagi-dev.atlassian.net/browse/QA-4347)
=> Added Slack Failure triggers for HQ & API #Attempt2

.github/workflows/hq-smoke-tests.yml
updated hq yml file to stop success email alerts in gitaction jobs
updated hq yml file to stop success email alerts in gitaction jobs
[Jira link](https://dimagi-dev.atlassian.net/browse/QA-4891)
=> QA-4891 removed conditions to send out success emails for hq smoke tests

.github/workflows/request_api.yml
updated request_api.yml file to stop success email alerts in gitaction jobs
updated request_api.yml file to stop success email alerts in gitaction jobs
[Jira link](https://dimagi-dev.atlassian.net/browse/QA-4891)
=> QA-4891 removed conditions to send out success emails for request api tests

HQSmokeTests/testCases/test_09_messaging.py, HQSmokeTests/testPages/android/android_screen.py, HQSmokeTests/testPages/data/import_cases_page.py, HQSmokeTests/testPages/messaging/messaging_page.py, HQSmokeTests/testPages/users/mobile_workers_page.py
Fixes for test_case_29_import_cases, test_case_44_create_cond_alert, test_case_46_keyword_creation and test_case_38_create_new_build_deploy_to_mobile
Fixes for the below testcase:
- test_case_29_import_cases - updated testcase according to the changes of [ticket](https://dimagi-dev.atlassian.net/browse/QA-4954)
- test_case_44_create_cond_alert - added the functionality to Restart Rule in case the processing stopped, also remove alert with same name if already created 
- test_case_46_keyword_creation - added functionality to remove all test keywords before the actual workflow, also updated links of delete and confirm delete button. Locators are different in both staging and prod, updated as a generic locator.
- test_case_38_create_new_build_deploy_to_mobile- updated browserstack app url …
=> QA-4981 Fixes for test_case_29_import_cases, test_case_44_create_cond_alert and test_case_46_keyword_creation

HQSmokeTests/testCases/test_02_users.py, HQSmokeTests/userInputs/user_inputs.py
removed pre-defined mobile usernames from user_input.py, added steps to use newly created usernames
removed pre-defined mobile usernames from user_input.py, added steps to use newly created usernames
[Jira link](https://dimagi-dev.atlassian.net/browse/QA-5025)
=> QA-5025 [Script Fix] Reuse of mobile workers in every run

Features/CaseSearch/requires.txt, Features/SplitScreenCaseSearch/requires.txt, USH_Apps/CO_BHA/requires.txt
Added missing py library to Casesearch, Multiselect and BHA scripts
Changes made in https://github.com/dimagi/dimagi-qa/pull/272/files#diff-98342b3005109a85796dd63672ea56fa071983d624c797fdd9d00df8a740e41e caused this
=> Added missing py lib

Features/MultiSelect/requires.txt
Added missing py library to Multiselect  scripts
Not sure which change caused this
=> Added missing requests lib to MS Scripts

HQSmokeTests/testCases/test_09_messaging.py, HQSmokeTests/testPages/applications/application_page.py, HQSmokeTests/testPages/data/reassign_cases_page.py, HQSmokeTests/testPages/messaging/messaging_page.py, HQSmokeTests/testPages/reports/report_page.py
Removed XFail from testcase_52, increased wait time of conditional_alert to 500, added soting step to reassign_cases
Removed XFail from testcase_52, increased wait time of conditional_alert to 500, added soting step to reassign_cases
[Jira link](https://dimagi-dev.atlassian.net/browse/QA-5668)
=> QA-5668 removed XFail from testcase_52, increased wait time of conditional_alert to 500, added soting step to reassign_cases

LocustScripts/commcarehq-bed-track.py
As is, if an exception occurs within `perform_a_search`, the wait time is skipped and the next iteration of the `for loop` is executed immediately. This change waits between searches even if there is an exception.
see Summary
=> wait after performing search even if an exception occurs

Features/MultiSelect/test_cases/test_02_multi_auto_select.py, HQSmokeTests/testCases/test_05_roles.py, HQSmokeTests/testCases/test_10_p1_p2_defects.py, HQSmokeTests/testPages/data/reassign_cases_page.py, HQSmokeTests/testPages/reports/report_page.py, HQSmokeTests/testPages/users/mobile_workers_page.py, HQSmokeTests/testPages/users/org_structure_page.py, HQSmokeTests/testPages/webapps/web_apps_page.py, common_utilities/selenium/webapps.py
Updated submit button locators
Updated submit button locators
[Jira link](https://dimagi-dev.atlassian.net/browse/QA-6444)
=> QA-6444 updated submit button locators

LocustScripts/commcarehq-bed-track-non-ideal-case.py
This is basically copy of `commcare-bed-track.py` which updates the searches in `commcare-bed-track.py` to follow following behaviour.
```
A non-faceted search 2 times per hour (instead of once per 5 seconds) and a faceted search 4 times per hour per user, ideally in a pattern of
Non-facteted search
Faceted search
Wait 20s
Faceted search
Wait ~30m
```
I have tested for timings locally, it works fine.
=> Add tests for non-ideal case

Features/CaseSearch/user_inputs/casesearch_user_inputs.py, common_utilities/selenium/webapps.py
Fix for casesearch split screen failure
Fix for casesearch split screen failure
[Jira link](https://dimagi-dev.atlassian.net/browse/QA-6444)
=> QA-6444 fix for casesearch split screen failure

Features/CaseSearch/test_cases/test_07_casesearch_data_registry.py, Features/CaseSearch/test_pages/casesearch_page.py, Features/SplitScreenCaseSearch/test_cases/test_07_casesearch_data_registry.py, HQSmokeTests/testPages/android/android_screen.py, HQSmokeTests/testPages/users/group_page.py, HQSmokeTests/testPages/users/org_structure_page.py
BS app URL update and CS alert locators update
BS app URL update and CS alert locators update
[Jira link](https://dimagi-dev.atlassian.net/browse/QA-6520)
=> QA-6520 BS app URL update and CS alert locators update

.github/workflows/bha-tests.yml, .github/workflows/case-search-tests.yml, .github/workflows/casesearch-split-screen-tests.yml, .github/workflows/hq-smoke-tests.yml, .github/workflows/multi-select-tests.yml, .github/workflows/request_api.yml, Features/CaseSearch/test_cases/conftest.py, Features/MultiSelect/test_cases/conftest.py, Features/SplitScreenCaseSearch/test_cases/conftest.py, HQSmokeTests/testCases/conftest.py, RequestAPI/testCases/conftest.py, USH_Apps/CO_BHA/test_cases/conftest.py, common_utilities/fixtures.py, pytest.ini
Made changes to all the active testsuite workflows for a better slack notification.
Made changes to all the active testsuite workflows for a better slack notification.
- The notifications will have the test pass, fail, skip, xfail, error counts
- There will be a red bar for failed executions and green for a success one
- A click button will directly download the report zip file.
[Jira link](https://dimagi-dev.atlassian.net/browse/QA-5310)
=> QA-5310 updated slack notification for all testsuits

.github/workflows/bha-tests.yml, .github/workflows/case-search-tests.yml, .github/workflows/casesearch-split-screen-tests.yml, .github/workflows/multi-select-tests.yml, HQSmokeTests/testPages/messaging/messaging_page.py, USH_Apps/CO_BHA/settings-sample.cfg, USH_Apps/CO_BHA/test_cases/conftest.py, USH_Apps/CO_BHA/test_cases/test_01_admit_client_and_locks.py, USH_Apps/CO_BHA/user_inputs/bha_user_inputs.py
Updated all USH yamls and fixed languages testcases
Updated all USH yamls and fixed languages testcases
[Jira link](https://dimagi-dev.atlassian.net/browse/QA-7048)
=> QA-7048 updated all ush yamls and fixed languages testcase

.github/workflows/es-tests.yml, .github/workflows/lookup-table.yml, ElasticSearchTests/testCases/conftest.py, ElasticSearchTests/testPages/reports/report_page.py, Features/Lookuptable/testCases/conftest.py, HQSmokeTests/testPages/applications/application_page.py, HQSmokeTests/testPages/reports/report_page.py
Updated locators to delete saved reports
Updated locators to delete saved reports
[Jira link](https://dimagi-dev.atlassian.net/browse/QA-7048)
=> QA-7048 updated locators to delete saved reports

HQSmokeTests/testPages/android/android_screen.py, HQSmokeTests/testPages/messaging/messaging_page.py, HQSmokeTests/testPages/users/org_structure_page.py, LocustScripts/update-scripts/commcarehq-referrals-search-for-beds-mw-login_single_case.py
Fix for staging failures and updated locust script
Fix for staging failures and updated locust script
- updated locators for org structure page
- created new locust file for load test
- added function to add default language to avoid error popup
- also updated apk in bs and updated the app url 
[Jira link](https://dimagi-dev.atlassian.net/browse/QA-7204)
=> QA-7204 fix for staging failures and updated locust script

LocustScripts/update-scripts/commcarehq-v2-it.py, LocustScripts/update-scripts/commcarehq-v2-rc.py, LocustScripts/update-scripts/project-config/co-carecoordination-perf/app_config_v2_it_test.json, LocustScripts/update-scripts/project-config/co-carecoordination-perf/app_config_v2_rc_test.json, LocustScripts/update-scripts/project-config/co-carecoordination-perf/mobile_worker_it_credentials.json, LocustScripts/update-scripts/project-config/co-carecoordination-perf/mobile_worker_rc_credentials.json, LocustScripts/update-scripts/project-config/co-carecoordination-perf/v2_it.yaml, LocustScripts/update-scripts/project-config/co-carecoordination-perf/v2_rc.yaml
Added the test scripts for V2 RC and V2 IT apps load tests
Added the test scripts for V2 RC and V2 IT apps load tests
- the V2 RC script creates households
- the V2 IT script reassigns household from 1 RC to another..
[Jira link](https://dimagi-dev.atlassian.net/browse/QA-7428)
=> QA-7428 added the scripts for Oncho load tests
