- .github/workflows/python-app.yml
Preparing to run tests on deploy success.
Docs for configuring the event:
https://docs.github.com/en/actions/reference/events-that-trigger-workflows#repository_dispatch
https://docs.github.com/en/rest/reference/repos#create-a-repository-dispatch-event
> Run tests on repository_dispatch deploy_success

- .github/workflows/python-app.yml
- HQSmokeTests/TestBase/environmentSetupPage.py
Note that this branch will merge into @kiran-tripathy's `kt/improvements` branch
> Add DIMAGIQA_ENV environment variable

- HQSmokeTests/testPages/others/login_page.py
Hi! I have added the code for dismissing the notification.
> added code to dismiss notification popup in the login_page.py

- HQSmokeTests/testPages/data/export_data_page.py
> added code to move back to previous screen in export_data_page.py

- HQSmokeTests/testPages/android/android_screen.py
Updated the app URL as the previous one expired.
> updated browserstack app URL in android_screen.py

- HQSmokeTests/testPages/data/export_data_page.py
Changes the date range to fix form & case exports failure as there were no data in the export files for the existing date range.
> Fixed Case Export & Form Exports failure

- .github/workflows/robot-framework.yml
Trigger our automated NY scripts after every prod deployment.
https://dimagi-dev.atlassian.net/browse/QA-4334
>  NY scripts after every prod deployment

- .github/workflows/robot-framework.yml
Changed condition for NY script prod deploy as it is triggering on both staging and prod deploy
https://dimagi-dev.atlassian.net/browse/QA-4334
- Framework/ Workflow Change
> changed condition for ny script prod trigger

- HQSmokeTests/testPages/android/android_screen.py
- HQSmokeTests/userInputs/user_inputs.py
Updated CommCare application on browserstack and updated browserstack url in script
> Updated Android Build on Browserstack

- HQSmokeTests/requires.txt
- HQSmokeTests/testCases/test_02_users.py
- HQSmokeTests/testCases/test_05_roles.py
- HQSmokeTests/testPages/base/base_page.py
- HQSmokeTests/testPages/data/export_data_page.py
- HQSmokeTests/testPages/users/group_page.py
- HQSmokeTests/testPages/users/mobile_workers_page.py
- HQSmokeTests/testPages/users/roles_permissions_page.py
Creating this PR for the follow fixes: test_cleanup_items_in_users_menu, test_case_04_deactivate_user
, test_case_04_reactivate_user, test_case_27_powerbi_tableau_integration_case, test_case_28_powerbi_tableau_integration_form
Made the below changes
- HQSmokeTests/testCases/test_02_users.py - updated test_cleanup_items_in_users_menu    
- HQSmokeTests/testPages/base/base_page.py - added new utility is_present() and wait_to_get_value()
- HQSmokeTests/testPages/data/export_data_page.py  - updated methods related to power_bi_tableau_integration_form and power_bi_tableau_integration_case
- HQSmokeTests/testPages/users/group_page.py  - added method to delete all test groups created via automation scripts
- HQSmokeTests/testPages/users/mobile_workers_page.py - updated methods related to …
> First set of script fixes

- HQSmokeTests/testCases/test_02_users.py
- HQSmokeTests/testPages/users/group_page.py
Made changes to fix the script failure for Download & Upload users as it was failing on both Prod and Staging.
> Fixed test_case_10_download_and_upload_users

- HQSmokeTests/testPages/applications/application_page.py
- HQSmokeTests/testPages/data/export_data_page.py
- HQSmokeTests/testPages/users/org_structure_page.py
This PR is for the fix of test_case_37_form_xml_download_upload
The test case was failing mostly because it was picking up an excel as the latest file in the folder, so I updated the function that returns the latest file name with the type of file we are looking for as a parameter. Default value for latest file is set as .xlsx.
> fix for test_case_37_form_xml_download_upload

- HQSmokeTests/testCases/test_04_locations.py
- HQSmokeTests/testPages/data/export_data_page.py
- HQSmokeTests/testPages/users/mobile_workers_page.py
- HQSmokeTests/testPages/users/org_structure_page.py
This PR is related to the failures in organization level screen
The test cases test_case_09_creation_organization_level and test_cleanup_items_in_locations_menu are failing due to QA-4374. hence marked them XFAIL when executed in staging. 
https://dimagi-dev.atlassian.net/browse/QA-4374)
> Addressing HQ script failures

- HQSmokeTests/testPages/data/export_data_page.py
This PR is for Form Export test failure on Staging
The form export test was failing mainly beause there were no forms in the downloaded export file. To fix that we have submitted new forms and also updated the date range for the date filter while downloading the export file to current date making it dynamic.
> Fix for Form Export test failure 

- HQSmokeTests/testPages/data/reassign_cases_page.py
- HQSmokeTests/testPages/users/org_structure_page.py
This PR is for test_case_30_reassign_case script failure 
Reassign cases was failing on staging & prod, so I have updated the assertion condition and user to which the case is being reassigned.
> Fix for Reassgin cases test failure

- HQSmokeTests/testCases/test_04_locations.py
- HQSmokeTests/testPages/users/mobile_workers_page.py
- HQSmokeTests/testPages/users/org_structure_page.py
This PR is for Form Export test failure on Staging.
The form export test was failing mainly beause there were no forms in the downloaded export file. To fix that we have submitted new forms and also updated the date range for the date filter while downloading the export file to current date making it dynamic.
This fix was approved in ns/smoke_fix.
> Fixes to export, reassign cases and archive locations failures

- HQSmokeTests/testPages/users/org_structure_page.py
- HQSmokeTests/testPages/webapps/web_apps_page.py
- HQSmokeTests/userInputs/user_inputs.py
Fixes for Testcase 58 and 56
For testcase 58, updated case property name, 
For testcase 56, added sleep in the assertion methods
> Fixes for Testcase 58 and 56

- .github/workflows/hq-smoke-tests.yml
corrected  the spelling of "deploy_success"  for the email subject line.
corrected  the spelling of "deploy_success"  for the email subject line.
> corrected a spelling in the hq-smoke-tests.yml

- .github/workflows/hq-smoke-tests.yml
- .github/workflows/ny-cict-robot-framework.yml
Cancel concurrent runs in scripts
More here: https://docs.github.com/en/actions/using-jobs/using-concurrency
[https://dimagi-dev.atlassian.net/browse/QA-4491](https://dimagi-dev.atlassian.net/browse/QA-4491)
> Handled concurrency for ny scripts and hq tests

- AppSprintPerformanceTests/CICT/CaptureReadings/CO_test_readings.py
- AppSprintPerformanceTests/CICT/CaptureReadings/NY_test_readings.py
- AppSprintPerformanceTests/CICT/UserInputs/co_cict_user_inputs.py
- AppSprintPerformanceTests/CICT/WorkflowActions/workflows/excel_actions.py
- AppSprintPerformanceTests/CICT/WorkflowActions/workflows/hq_actions.py
Additional changes to users,inputs and form name
[https://dimagi-dev.atlassian.net/browse/QA-4385](https://dimagi-dev.atlassian.net/browse/QA-4385)
https://confluence.dimagi.com/display/GTD/Capturing+app+workflow+performance
> [CO Perf]Additional changes to users,inputs and form name

- HQSmokeTests/testPages/android/android_screen.py
Updated the Browser Stack app Url
Updated the Browser Stack app Url
NA
> updated browser stack app url

- RequestAPI/testCases/test_10_misc.py
- RequestAPI/testCases/test_11_curl_apis.py
Removed testcase for data forwarding
Removed testcase for data forwarding as it is deprecated and renamed the testcases that follows
NA
> Data Forwarding testcase removed

- .github/workflows/sprint-app-perf.yml
- AppSprintPerformanceTests/CICT/CaptureReadings/conftest.py
- AppSprintPerformanceTests/CICT/requires.txt
- AppSprintPerformanceTests/CICT/settings-sample.cfg
- HQSmokeTests/testCases/test_01_others.py
- common_utilities/hq_login/login_page.py
Made changes to 2FA workflows to test https://dimagi-dev.atlassian.net/browse/QA-4594
[https://dimagi-dev.atlassian.net/browse/QA-4594](https://dimagi-dev.atlassian.net/browse/QA-4594)
> QA-4594 made changes to 2FA workflows

- .github/workflows/request_api.yml
Updated email recipient list of request API
Updated email recipient list of request API in the yml file
> Updated email recipients for request API

- HQSmokeTests/testPages/android/android_screen.py
- HQSmokeTests/testPages/data/auto_case_update_page.py
- HQSmokeTests/testPages/users/org_structure_page.py
- common_utilities/selenium/base_page.py
Updated the Browser Stack app Url, fixed testcase test_case_32_auto_case_update and test_case_56_archive_unarchive_location
Updated the Browser Stack app Url, fixed testcase test_case_32_auto_case_update and test_case_56_archive_unarchive_location
NA
> HQ SmokeTest script fixes

- HQSmokeTests/testCases/test_06_data.py
- HQSmokeTests/testPages/data/auto_case_update_page.py
- HQSmokeTests/testPages/data/export_data_page.py
- HQSmokeTests/testPages/data/import_cases_page.py
- common_utilities/selenium/base_page.py
added method to delete all test rules created by scripts, added new utility to wait until progress bar is complete for the export testcases
added method to delete all test rules created by scripts, added new utility to wait until progress bar is complete for the export testcases
[Jira Ticket](https://dimagi-dev.atlassian.net/browse/QA-4576)
> added method to delete all test rules created by scripts

- .github/workflows/request_api.yml
- HQSmokeTests/testPages/data/auto_case_update_page.py
- HQSmokeTests/testPages/data/export_data_page.py
Updated steps to fix export downloads and rule deletions
Updated steps to fix export downloads and rule deletions
> QA-4576 updated a few steps to fix export download and rule deletion

- HQSmokeTests/testPages/home/home_page.py
- RequestAPI/testCases/test_09_fixtures.py
- RequestAPI/userInputs/user_inputs.py
Added new domain and fixed test_case_30 failure for Request API testcases. Also update home_page.py of HQSmokeTest.
Added new domain and fixed test_case_30 failure for Request API testcases. Also update home_page.py of HQSmokeTest.
> QA-4576 added new domain and fixed test_case_30 failure for Request API testcases

- HQSmokeTests/testCases/test_06_data.py
- HQSmokeTests/testCases/test_08_reports.py
- HQSmokeTests/testPages/data/manage_forms_page.py
- HQSmokeTests/testPages/home/home_page.py
- HQSmokeTests/testPages/reports/report_page.py
- HQSmokeTests/testPages/users/mobile_workers_page.py
- HQSmokeTests/testPages/webapps/web_apps_page.py
Updated steps to fix failures of testcases 15_16 and 38
Updated steps to fix failures of testcases 15_16 and 38.
> fix for testcase 15_16 and 38

- .github/workflows/request_api.yml
- RequestAPI/testMethods/base.py
added ULR print statement to base.py and env name to email subject in yml for Request API
added ULR print statement to base.py and env name to email subject in yml for Request API
> QA-4576 added ULR print statement to base.py and env name to email subject in yml for Request API

- .github/workflows/request_api.yml
added env name to both email subject in yml for Request API and also fixed a syntax in the yaml
added env name to both email subject in yml for Request API and also fixed a syntax in the yaml
> QA-4576 added env name to both email subject in yml for Request API

- HQSmokeTests/testCases/test_01_others.py
- HQSmokeTests/testCases/test_02_users.py
- HQSmokeTests/testCases/test_04_integration_exports.py
- HQSmokeTests/testCases/test_04_locations.py
- HQSmokeTests/testCases/test_05_roles.py
- HQSmokeTests/testCases/test_06_data.py
- HQSmokeTests/testCases/test_07_applications.py
- HQSmokeTests/testCases/test_08_reports.py
- HQSmokeTests/testCases/test_09_messaging.py
- HQSmokeTests/testPages/home/home_page.py
- HQSmokeTests/testPages/users/mobile_workers_page.py
Removed the XFail tag from testcase 59, also made changes to home page so that the testcases do not get stuck on failure of previous testcase.
Removed the XFail tag from testcase 59, also made changes to home page so that the testcases do not get stuck on failure of previous testcase.
> QA-4576 commented the xfail statement for testcase 59

- Features/CaseSearch/test_cases/test_01_casesearch_workflows.py
- Features/CaseSearch/test_cases/test_02_casesearch_configs.py
- Features/CaseSearch/test_cases/test_03_casesearch_misc.py
- Features/CaseSearch/test_cases/test_04_casesearch_fuzzy_search.py
- Features/CaseSearch/test_cases/test_05_casesearch_inline_search.py
- Features/CaseSearch/test_pages/casesearch_page.py
- Features/CaseSearch/user_inputs/casesearch_user_inputs.py
- common_utilities/selenium/webapps.py
Added Case Search Workflows for Inline Search
[Inline Case Search tests in Case Search Regression Plan](https://docs.google.com/spreadsheets/d/1sPLEAJFlhztZ656TH4jk-tjUbhu_YE-8dvVdgiy3xQQ/edit#gid=894360002)
[https://dimagi-dev.atlassian.net/browse/QA-4182](https://dimagi-dev.atlassian.net/browse/QA-4182)
> Inline Case Search Test Cases

- .github/workflows/request_api.yml
- HQSmokeTests/testPages/android/android_screen.py
Updated bs url for android test and updated request API workflow yml
Updated bs url for android test and updated request API workflow yml
> QA-4576 updated bs url for android test and updated request API workflow yml

- HQSmokeTests/testCases/test_04_locations.py
- HQSmokeTests/testCases/test_06_data.py
- HQSmokeTests/testCases/test_07_applications.py
- HQSmokeTests/testPages/users/org_structure_page.py
Removed xfail marks from testcases test_case_58_deduplicate_cases and test_case_40_app_preview
Removed xfail marks from testcases test_case_58_deduplicate_cases and test_case_40_app_preview
> QA-4576 removed xfail marks

- .github/workflows/case-search-tests.yml
- Features/CaseSearch/requires.txt
Added missing library in requires.text 
Removed parallel runs
> Minor updates to case search scripts

- .github/workflows/case-search-tests.yml
Removed --rootdir from pytest command
> Updated case search ci

- HQSmokeTests/testPages/android/android_screen.py
Updated bs url for android test.
Updated bs url for android test.
> QA-4576 updated app url for android test case

- Features/CaseSearch/requires.txt
- Features/CaseSearch/test_cases/test_01_casesearch_workflows.py
- Features/CaseSearch/test_cases/test_02_casesearch_configs.py
- Features/CaseSearch/test_cases/test_03_casesearch_misc.py
- Features/CaseSearch/test_cases/test_04_casesearch_fuzzy_search.py
- Features/CaseSearch/test_cases/test_05_casesearch_inline_search.py
- Features/CaseSearch/test_pages/casesearch_page.py
- Features/CaseSearch/user_inputs/casesearch_user_inputs.py
- HQSmokeTests/testPages/users/mobile_workers_page.py
- common_utilities/selenium/webapps.py
Fixed failing test cases for case search
> Fixed failing test cases for case search

- .github/workflows/case-search-tests.yml
- .github/workflows/hq-smoke-tests.yml
- .github/workflows/request_api.yml
Corrected typo in trigger slack message
[https://dimagi-dev.atlassian.net/browse/QA-4347](https://dimagi-dev.atlassian.net/browse/QA-4347)
> Corrected typo in slack trigger message

- HQSmokeTests/testPages/applications/application_page.py
Added assertion to verify that Released button is successfully pressed.
Added assertion to verify that Released button is successfully pressed.
[Jira link](https://dimagi-dev.atlassian.net/browse/QA-4726)
> added Released button pressed assertion

- HQSmokeTests/testPages/messaging/messaging_page.py
Fix for testcase 44.
Fix for testcase 44
[Jira link](https://dimagi-dev.atlassian.net/browse/QA-4338)
> fix for testcase 44

- HQSmokeTests/testPages/android/android_screen.py
updated browserstack app url
updated browserstack app url
[Jira link](https://dimagi-dev.atlassian.net/browse/QA-4338)
> updated browserstack app url

- Features/CaseSearch/test_cases/test_01_casesearch_workflows.py
- Features/CaseSearch/test_cases/test_02_casesearch_configs.py
- Features/CaseSearch/test_cases/test_03_casesearch_misc.py
- Features/CaseSearch/test_pages/casesearch_page.py
- Features/CaseSearch/user_inputs/casesearch_user_inputs.py
- common_utilities/selenium/base_page.py
- common_utilities/selenium/webapps.py
Update to Case Search Scripts to Address Failures 
Failures were mostly due to [QA-4817](https://dimagi-dev.atlassian.net/browse/QA-4817) and app setup changes in the recent past -- those have been fixed in this PR.
[https://dimagi-dev.atlassian.net/browse/QA-4895](https://dimagi-dev.atlassian.net/browse/QA-4895)
[QA-4817]: https://dimagi-dev.atlassian.net/browse/QA-4817?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [QA-4895] Updates to Case Search Scripts to Address Failures

- Features/CaseSearch/test_pages/casesearch_page.py
Update casesearch plus multiselect test
> Update casesearch plus multiselect test

- HQSmokeTests/testPages/data/reassign_cases_page.py
updated locator that was failing testcase 30
updated locator that was failing testcase 30
[Jira link](https://dimagi-dev.atlassian.net/browse/QA-4913)
> QA-4913 updated locator failing testcase 30

- .github/workflows/multi-select-tests.yml
- Features/MultiSelect/test_cases/test_01_multi_select.py
- Features/MultiSelect/test_cases/test_02_multi_auto_select.py
- Features/MultiSelect/test_pages/multiselect_page.py
- Features/MultiSelect/user_inputs/multiselect_user_inputs.py
Tested MultiSelect Script (which was blcked due a couple of USH bugs) and fixed script erreors
Also a tiny update to the slack message to easily idenity MultiSelect Scripts
[https://dimagi-dev.atlassian.net/browse/QA-206](https://dimagi-dev.atlassian.net/browse/QA-206)
> [QA-206] Multi Select Script Fixes

- Features/CaseSearch/test_cases/test_03_casesearch_misc.py
- Features/CaseSearch/test_cases/test_07_casesearch_data_registry.py
> Uncommented some case search test cases

- Features/CaseSearch/test_cases/test_07_casesearch_data_registry.py
Handled an expected error in case search scripts
> Handled an expected error in case search scripts

- Features/CaseSearch/test_cases/test_05_casesearch_inline_search.py
- Features/CaseSearch/user_inputs/casesearch_user_inputs.py
Added test case for old case search input instance
[Relevant test case](https://docs.google.com/spreadsheets/d/13vUbmbMqtFWwjvmvuST66p3X5u6sLNnBrLWQICx_iaQ/edit#gid=894360002&range=C11)
[https://dimagi-dev.atlassian.net/browse/QA-4853](https://dimagi-dev.atlassian.net/browse/QA-4853)
> [QA-4853] Added test case for old case search input instance

- HQSmokeTests/testPages/messaging/messaging_page.py
Added try-except for  test_case_44_create_cond_alert 
Added try-except for  test_case_44_create_cond_alert 
[Jira link](https://dimagi-dev.atlassian.net/browse/QA-4981)
> QA-4981 added try-exception for test case 44

- HQSmokeTests/testPages/messaging/messaging_page.py
added a missing step for  test_case_43_broadcast 
added a missing step for  test_case_43_broadcast 
[Jira link](https://dimagi-dev.atlassian.net/browse/QA-5012)
> QA-5012 fix for testcase 43

- .github/workflows/case-search-tests.yml
- .github/workflows/hq-smoke-tests.yml
- .github/workflows/multi-select-tests.yml
- .github/workflows/request_api.yml
updated hq smoke test, request api, case search and multi select ymls to separate environments during concurrency execution
updated hq smoke test, request api, case search and multi select ymls to separate environments during concurrency execution
[Jira link](https://dimagi-dev.atlassian.net/browse/QA-5026)
> QA-5026 updated ymls to separate environments during concurrency execution

- .github/workflows/case-search-tests.yml
- Features/CaseSearch/test_cases/test_02_casesearch_configs.py
- Features/CaseSearch/test_cases/test_03_casesearch_misc.py
- Features/CaseSearch/test_cases/test_07_casesearch_data_registry.py
- Features/CaseSearch/test_pages/casesearch_page.py
- Features/CaseSearch/user_inputs/casesearch_user_inputs.py
Expanded upon case search test cases
- Added test cases for:
- [Case Search Dropdown Changes](https://dimagi-dev.atlassian.net/browse/QA-4993)
- [Checkbox Selection in Case Search UI](https://dimagi-dev.atlassian.net/browse/QA-1099)
- Expanded upon test cases for data registry for cases on the same domain (raised in [QA-4995](https://dimagi-dev.atlassian.net/browse/QA-4995))
- Disabled reruns on failures
[https://dimagi-dev.atlassian.net/browse/QA-4853](https://dimagi-dev.atlassian.net/browse/QA-4853)
[QA-4995]: https://dimagi-dev.atlassian.net/browse/QA-4995?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [QA-4853] Expanded upon case search test cases

- Features/CaseSearch/test_cases/test_02_casesearch_configs.py
Tiny fix for a failing test case 
The lookup table was updated on the domain, so changing selection value
> Tiny fix for a failing test case

- Features/CaseSearch/test_cases/test_04_casesearch_fuzzy_search.py
- Features/CaseSearch/test_pages/casesearch_page.py
Updates to case search scripts
-  Removed user creation on every run
- Added filter to remove blanks to fix a false failure
> Updates to case search scripts

- Features/CaseSearch/test_cases/test_02_casesearch_configs.py
- Features/CaseSearch/test_pages/casesearch_page.py
Updated script to reference updated HTML elements due to changes in QA-4993
[Regression Testing for Case Search Dropdown Changes](https://dimagi-dev.atlassian.net/browse/QA-4993)
> [QA-4993] Updated the references due to HTML changes

- HQSmokeTests/testCases/test_03_exports.py
- HQSmokeTests/testCases/test_04_integration_exports.py
- HQSmokeTests/testCases/test_06_data.py
- HQSmokeTests/testPages/data/export_data_page.py
- HQSmokeTests/testPages/home/home_page.py
fixed data menu navigation for exports and data testcases
fixed data menu navigation for exports and data testcases
[Jira link](https://dimagi-dev.atlassian.net/browse/QA-5153)
> QA-5153 fixed data menu navigation for exports and data testcases

- RequestAPI/testCases/test_10_misc.py
Removed Xfail tag for Login/Logout tracking API testcase with no parameters
Removed Xfail tag for Login/Logout tracking API testcase with no parameters
[Jira link](https://dimagi-dev.atlassian.net/browse/QA-5160)
> QA-5160 removed xfail

- Features/CaseSearch/user_inputs/casesearch_user_inputs.py
- Features/MultiSelect/user_inputs/multiselect_user_inputs.py
Updated app names on HQ, so renaming in scripts
> Renamed apps on HQ

- HQSmokeTests/testPages/applications/application_page.py
added pop-up accept step in the method form_builder_exploration
added pop-up accept step in the method form_builder_exploration
[Jira link](https://dimagi-dev.atlassian.net/browse/QA-5212)
> QA-5212 added pop-up accept step in the method form_builder_exploration

- Features/CaseSearch/requires.txt
- Features/MultiSelect/requires.txt
Updated selenium version on the requires.txt for case search and multiselect testsuites
> updated selenium versions for case search and multiselect testsuites

- Features/CaseSearch/constants.py
- Features/CaseSearch/test_cases/test_02_casesearch_configs.py
- Features/MultiSelect/test_cases/test_01_multi_select.py
- Features/MultiSelect/test_pages/multiselect_page.py
- Features/MultiSelect/user_inputs/multiselect_user_inputs.py
Added test case for multi-select workflow with case tiles
- [Added this test case](https://docs.google.com/spreadsheets/d/1dCcjfufT4t0J_SPwRCkR0cEYfegg18hz6iPcgMOqpes/edit#gid=1746370823&range=C23)
- Minor navigation update due to app setup changes
[Multi-select for case list tiles ](https://dimagi-dev.atlassian.net/browse/QA-5100)
> [QA-5100] Case tiles and multiselect

- Features/CaseSearch/README.md
- Features/MultiSelect/README.md
- HQSmokeTests/README.md
> Updated READMEs

- Features/CaseSearch/test_cases/test_02_casesearch_configs.py
Added wait to fix a failing test case
> Added wait to fix a failing test case

- HQSmokeTests/userInputs/user_inputs.py
updated the new email ID for web user invitation
updated the new email ID for web user invitation
[https://dimagi-dev.atlassian.net/browse/QA-5311](https://dimagi-dev.atlassian.net/browse/QA-5311)
> QA-5311 updated the email ID for web user invitation

- Features/CaseSearch/test_cases/test_02_casesearch_configs.py
Updated script to reference updated HTML elements
Updated references due to HTML changes
> Updated references due to HTML changes

- Features/CaseSearch/test_cases/test_02_casesearch_configs.py
Updated script to reference updated HTML elements
Updated references due to HTML changes
> #2 Updated references due to HTML changes

- HQSmokeTests/testCases/test_08_reports.py
- HQSmokeTests/testPages/messaging/messaging_page.py
- HQSmokeTests/testPages/reports/report_page.py
- HQSmokeTests/testPages/users/mobile_workers_page.py
- HQSmokeTests/testPages/users/roles_permissions_page.py
- common_utilities/selenium/base_page.py
Added new testcase for cleaning all saved reports and report cases. Also fix for messaging failures.
Added new testcase for cleaning all saved reports and report cases. Also fix for messaging failures.
[Jira link](https://dimagi-dev.atlassian.net/browse/QA-5360)
> QA-5360 fixes for messaging and reports failures, addition of report deletion testcase

- HQSmokeTests/testPages/home/home_page.py
- HQSmokeTests/testPages/users/mobile_workers_page.py
- HQSmokeTests/testPages/users/org_structure_page.py
- common_utilities/selenium/base_page.py
Added login call in except block for open menus
Added login call in except block for open menus
[Jira link](https://dimagi-dev.atlassian.net/browse/QA-5410)
> QA-5410 added login call in except block for open menus

- HQSmokeTests/testPages/data/data_dictionary_page.py
Updated data dictionary link locator
Updated data dictionary link locator
[Jira link](https://dimagi-dev.atlassian.net/browse/QA-5470)
> QA-5470 Updated data dictionary link locator

- .github/workflows/bha-tests.yml
- USH_Apps/CO_BHA/test_cases/conftest.py
More updates to BHA Script 
- Updated yml variables
[https://dimagi-dev.atlassian.net/browse/QA-4970](https://dimagi-dev.atlassian.net/browse/QA-4970 )
> [QA-4970] Updates to BHA Script - #3

- USH_Apps/CO_BHA/test_cases/test_04_conditional_alert_triggers.py
More updates to BHA Script 
- Some changes to cond alert workflow
[https://dimagi-dev.atlassian.net/browse/QA-4970](https://dimagi-dev.atlassian.net/browse/QA-4970 )
> [QA-4970] Updates to BHA Script - #4

- common_utilities/selenium/webapps.py
> Added a missing assert

- Features/CaseSearch/user_inputs/casesearch_user_inputs.py
- Features/MultiSelect/test_cases/test_01_multi_select.py
Updates to Multi Select Scripts
Fix for [https://dimagi-dev.atlassian.net/browse/QA-5457](https://dimagi-dev.atlassian.net/browse/QA-5457)
[https://dimagi-dev.atlassian.net/browse/QA-5514](https://dimagi-dev.atlassian.net/browse/QA-5514)
> [QA-5514] Updates to Multi Select Scripts

- HQSmokeTests/testPages/reports/report_page.py
- common_utilities/selenium/webapps.py
Script updates
- Handled 500 error
- Added filter of present date in the message history
> [QA-4970] Updates to BHA Script - #6

- Features/SplitScreenCaseSearch/test_cases/test_01_casesearch_workflows.py
- Features/SplitScreenCaseSearch/test_cases/test_02_casesearch_configs.py
- Features/SplitScreenCaseSearch/test_cases/test_03_casesearch_misc.py
- Features/SplitScreenCaseSearch/test_cases/test_04_casesearch_fuzzy_search.py
- Features/SplitScreenCaseSearch/test_cases/test_05_casesearch_inline_search.py
- Features/SplitScreenCaseSearch/test_cases/test_06_casesearch_multi_select.py
- Features/SplitScreenCaseSearch/test_cases/test_07_casesearch_data_registry.py
- common_utilities/selenium/webapps.py
Removed assert for search again
Removed assert for search again
> Removed assert for search again

- Features/MultiSelect/test_cases/test_01_multi_select.py
- USH_Apps/CO_BHA/test_cases/test_01_admit_client_and_locks.py
- USH_Apps/CO_BHA/test_cases/test_02_discharge_client.py
- USH_Apps/CO_BHA/test_cases/test_03_user_management.py
- common_utilities/selenium/webapps.py
Handled errors in MS and BHA scripts
Handled errors in MS and BHA scripts
> Handled errors

- Features/MultiSelect/test_cases/test_01_multi_select.py
- common_utilities/selenium/webapps.py
> Removed assert

- USH_Apps/CO_BHA/test_cases/test_04_conditional_alert_triggers.py
- common_utilities/selenium/webapps.py
> Minor updates to the scripts

- Features/CaseSearch/requires.txt
- Features/SplitScreenCaseSearch/requires.txt
- USH_Apps/CO_BHA/requires.txt
Added missing requests library to Casesearch, Multiselect and BHA scripts
Changes made in https://github.com/dimagi/dimagi-qa/pull/267/ caused this, specifically this one https://github.com/dimagi/dimagi-qa/pull/267/files#diff-0ca6b3fceefbb57c8dbcbbd373ed0b8e32150c15f8e475a28514b876638aba21
> Added missing requests library

- Features/CaseSearch/requires.txt
- Features/SplitScreenCaseSearch/requires.txt
- HQSmokeTests/testPages/android/android_screen.py
- HQSmokeTests/testPages/data/reassign_cases_page.py
- USH_Apps/CO_BHA/requires.txt
Updated browser stack app url, added openpyxl in requires.txt for case search and bha suites, a little modification to reassigncases
Updated browser stack app url, added openpyxl in requires.txt for case search and bha suites, a little modification to reassigncases
[Jira link](https://dimagi-dev.atlassian.net/browse/QA-5668)
> QA-5668 updated browser stack app url, added openpyxl in requires.txt for case search and bha suites, a little modification to reassigncases

- HQSmokeTests/testCases/test_02_users.py
- HQSmokeTests/testCases/test_08_reports.py
- HQSmokeTests/testPages/data/export_data_page.py
- HQSmokeTests/testPages/reports/report_page.py
- HQSmokeTests/testPages/users/mobile_workers_page.py
Fix for test_case_54_add_custom_user_data_profile_to_mobile_worker failure
Fix for test_case_54_add_custom_user_data_profile_to_mobile_worker failure
[Jira link](https://dimagi-dev.atlassian.net/browse/QA-5691)
> QA-5691 fix for testcase 54

- .github/workflows/lookup-table.yml
Made 2 sections for sending slack updates: one for success and one for failure.
Link to the [Jira ticket](https://dimagi-dev.atlassian.net/browse/QA-64)
> QA-64 added 2 sections for slack updates

- .github/workflows/request_api.yml
- RequestAPI/testCases/test_01_mobile_worker.py
- RequestAPI/testCases/test_04_application.py
- RequestAPI/testCases/test_06_cases.py
- RequestAPI/testCases/test_08_locations.py
- RequestAPI/testCases/test_10_misc.py
Fixed prod URL trigger in yml and added dependency on testcases
Fixed prod URL trigger in yml and added dependency on testcases
[Jira link](https://dimagi-dev.atlassian.net/browse/QA-5742)
> QA-5742 made a little change to yml and added dependency on testcases

- .gitignore
- HQSmokeTests/testPages/android/android_screen.py
Updated bs app url and gitignore
Updated bs app url and gitignore
[Jira link](https://dimagi-dev.atlassian.net/browse/QA-5784)
> QA-5784 updated bs app url and gitignore

- HQSmokeTests/testPages/reports/report_page.py
- HQSmokeTests/userInputs/user_inputs.py
Added validation for group name in test_case_70_case_owner_list and test_case_71_case_owner_list_explorer
Added validation for group name in test_case_70_case_owner_list and test_case_71_case_owner_list_explorer.
[Jira link](https://dimagi-dev.atlassian.net/browse/QA-5800)
> QA-5800 added validation for group name in testcases 70 and 71

- HQSmokeTests/testPages/users/mobile_workers_page.py
Updated locator of Edit User Fields
Updated locator of Edit User Fields
[Jira link](https://dimagi-dev.atlassian.net/browse/QA-5831)
> QA-5831 updated locator of Edit User Fields

- HQSmokeTests/testPages/android/android_screen.py
- HQSmokeTests/testPages/data/copy_cases_page.py
- HQSmokeTests/testPages/data/reassign_cases_page.py
- HQSmokeTests/testPages/users/mobile_workers_page.py
Updated bs app url and fixed reassign and copy cases failures
Updated bs app url and fixed reassign and copy cases failures
[Jira link](https://dimagi-dev.atlassian.net/browse/QA-5884)
> QA-5884 updated bs app url and fixed reassign and copy cases failures

- HQSmokeTests/testPages/webapps/web_apps_page.py
Updated submit locator for webapps forms
Updated submit locator for webapps forms
[Jira link](https://dimagi-dev.atlassian.net/browse/QA-5884)
> QA-5884 updated submit locator for webapps forms

- common_utilities/selenium/webapps.py
Updated submit locator for webapps forms in common utilities
Updated submit locator for webapps forms in common utilities
[Jira link](https://dimagi-dev.atlassian.net/browse/QA-5884)
> QA-5884 updated submit button locator for webapps common utility

- HQSmokeTests/testPages/applications/app_preview.py
- HQSmokeTests/testPages/webapps/web_apps_page.py
Updated home button locator in webapps and app_preview
Updated home button locator in webapps and app_preview
[Jira link](https://dimagi-dev.atlassian.net/browse/QA-5884)
> QA-5884 updated home button locator in webapps and app_preview

- Features/CaseSearch/test_pages/casesearch_page.py
- Features/MultiSelect/test_pages/multiselect_page.py
- HQSmokeTests/testPages/data/export_data_page.py
Fix for double continue buttons and export page wait time
Fix for double continue buttons and export page wait time
[Jira link](https://dimagi-dev.atlassian.net/browse/QA-5944)
> QA-5944 fix for double continue buttons and export page wait time

- Features/CaseSearch/test_pages/casesearch_page.py
- HQSmokeTests/testPages/applications/application_page.py
- HQSmokeTests/testPages/email/email_verification.py
- HQSmokeTests/testPages/reports/report_page.py
Updated steps for casesearch testcase test_case_01_multiple_selected_cases_accessible_on_form
Updated steps for casesearch testcase test_case_01_multiple_selected_cases_accessible_on_form
[Jira link](https://dimagi-dev.atlassian.net/browse/QA-5989)
> QA-5989 updated steps for casesearch testcase test_case_01_multiple_selected_cases_accessible_on_form

- .github/workflows/hq-smoke-tests.yml
- .github/workflows/request_api.yml
- HQSmokeTests/testPages/applications/app_preview.py
- USH_Apps/CO_BHA/test_cases/test_01_admit_client_and_locks.py
Fix for HQSmokeTest testcase 40, BHA script dependency, added pruthvi's email in ymls
Fix for HQSmokeTest testcase 40, BHA script dependency, added pruthvi's email in ymls
[Jira link](https://dimagi-dev.atlassian.net/browse/QA-6024)
> QA-6024 fix for HQSmokeTest testcase 40, BHA script dependency, added pruthvi's email in ymls

- HQSmokeTests/testPages/users/web_user_page.py
Updated locator for delete invitation button
Updated locator for delete invitation button
[Jira link](https://dimagi-dev.atlassian.net/browse/QA-6059)
> QA-6059 updated locator for delete invitation button

- HQSmokeTests/testPages/data/data_dictionary_page.py
- HQSmokeTests/testPages/data/export_data_page.py
Import button, download button locator update and parent-child case imports fix
Import button, download button locator update and parent-child case imports fix
[Jira link](https://dimagi-dev.atlassian.net/browse/QA-6147)
> QA-6147 import button, download button locator update and parent-child case imports fix

- .github/workflows/bha-tests.yml
- .github/workflows/case-search-tests.yml
- .github/workflows/casesearch-split-screen-tests.yml
- .github/workflows/hq-smoke-tests.yml
- .github/workflows/multi-select-tests.yml
- .github/workflows/request_api.yml
Added condition to all active github yml files to push Prod deploy reports to a separate channel
Added condition to all active github yml files to push Prod deploy reports to a separate channel
[Jira link](https://dimagi-dev.atlassian.net/browse/QA-6145)
> QA-6145 added condition to publish reports to slack prod channel

- .github/workflows/bha-tests.yml
- .github/workflows/case-search-tests.yml
- .github/workflows/casesearch-split-screen-tests.yml
- .github/workflows/hq-smoke-tests.yml
- .github/workflows/multi-select-tests.yml
- .github/workflows/request_api.yml
Updated yaml files of all the active testsuites with Slack Pass and Failed jobs and also corrected webhook url for Case Search.
Updated yaml files of all the active testsuites with Slack Pass and Failed jobs and also corrected webhook url for Case Search. 
[Jira link](https://dimagi-dev.atlassian.net/browse/QA-6145)
> Qa 6145 Updated yaml files of all the active testsuites with Slack Pass and Failed jobs and also corrected webhook url for Case Search.

- HQSmokeTests/testPages/users/web_user_page.py
- RequestAPI/testCases/test_10_misc.py
Updated  locator for update role button and marked test_case_39_login_logout_tracking_api_no_params skip
Updated  locator for update role button and marked test_case_39_login_logout_tracking_api_no_params skip
[Jira link](https://dimagi-dev.atlassian.net/browse/QA-6167)
> QA-6167 update locator for update role button and marked test_case_39_login_logout_tracking_api_no_params skip

- USH_Apps/CO_BHA/test_cases/test_03_user_management.py
- USH_Apps/CO_BHA/user_inputs/bha_user_inputs.py
- common_utilities/selenium/webapps.py
We are working on updating the app to check for the values of forms
> Added a change to check the user assigned clinics in the user management form

- HQSmokeTests/testPages/android/android_screen.py
Updated bs app url for the month
Updated bs app url for the month
[Jira link](https://dimagi-dev.atlassian.net/browse/QA-6176)
> QA-6176 updated bs app url for the month

- Features/CaseSearch/test_cases/test_07_casesearch_data_registry.py
- USH_Apps/CO_BHA/test_cases/test_01_admit_client_and_locks.py
- USH_Apps/CO_BHA/test_cases/test_02_discharge_client.py
- USH_Apps/CO_BHA/test_pages/bha_app_pages.py
- common_utilities/selenium/webapps.py
Fix for BHA failures
Fix for BHA failures
[Jira link](https://dimagi-dev.atlassian.net/browse/QA-6176)
> QA-6176 fix for BHA failures

- .github/workflows/bha-tests.yml
- .github/workflows/case-search-tests.yml
- .github/workflows/casesearch-split-screen-tests.yml
- .github/workflows/lookup-table.yml
- .github/workflows/multi-select-tests.yml
- ElasticSearchTests/testCases/test_12_device_logs_details.py
- ElasticSearchTests/testCases/test_13_sms_usage.py
- ElasticSearchTests/testCases/test_14_case_list_explorer.py
- ElasticSearchTests/testCases/test_15_message_log.py
- ElasticSearchTests/testPages/case_list_explorer/case_list_explorer_page.py
- ElasticSearchTests/testPages/daily_form_activity/daily_form_activity_page.py
- ElasticSearchTests/testPages/device_logs_details/device_logs_details_page.py
- ElasticSearchTests/testPages/message_log/message_log_page.py
- ElasticSearchTests/testPages/raw_forms_errors_duplicates/raw_forms_errors_duplicates_page.py
- ElasticSearchTests/testPages/sms_usage/sms_usage_page.py
- ElasticSearchTests/testPages/submit_history/submit_history_page.py
- ElasticSearchTests/testPages/worker_activity/worker_activity_page.py
- ElasticSearchTests/userInputs/user_inputs.py
- Features/CaseSearch/test_cases/test_07_casesearch_data_registry.py
- Features/SplitScreenCaseSearch/test_cases/test_07_casesearch_data_registry.py
- HQSmokeTests/testPages/email/email_verification.py
- common_utilities/selenium/base_page.py
Added the feasible testcases of Device Log Details tab of Reports test plan
Added the feasible testcases of Device Log Details tab of Reports test plan
- Submit History
[Jira link](https://dimagi-dev.atlassian.net/browse/QA-5485)
> QA-5485 added testcases for tab Device Log Details

- LocustScripts/commcarehq-bed-track.py
Improve logging to Bed Track Script
- adds reference to mobile user for each logged item so that it traces back to the user
- adds message to log when assertion fails. As is, the exception is an empty string if an assertion fails within the try block.
> Improve logging to Bed Track Script

- HQSmokeTests/testCases/test_10_p1_p2_defects.py
- HQSmokeTests/testPages/applications/app_preview.py
- HQSmokeTests/testPages/messaging/messaging_page.py
- HQSmokeTests/testPages/users/group_page.py
Added step to wait till loading is complete
Added step to wait till loading is complete
[Jira link](https://dimagi-dev.atlassian.net/browse/QA-6354)
> QA-6354 added step for loading popup

- LocustScripts/README.md
- LocustScripts/commcarehq-bed-track.py
- LocustScripts/commcarehq-referrals-outgoing-referrals.py
- LocustScripts/commcarehq-referrals-search-for-beds.py
- LocustScripts/common/web_apps.py
- LocustScripts/formplayer.py
- LocustScripts/project-config/co-carecoordination-perf/config.yaml
- LocustScripts/user/models.py
This does a lot of refactoring to improve code reuse and readability.
It also has one major functional change which is the last commit where we no longer user random wait times between requests but instead use the built in wait provided by locust. This in combination with the change from a constant / random wait time to a [constant_pace](https://docs.locust.io/en/stable/api.html#locust.wait_time.constant_pacing) wait function has the effect of producing a constant request rate per user.
With the changes as it stands we can expect an approximate request rate of one every 5s. In order to a rate of 30/s we would need 5*30 (150) concurrent users.
> refactor bed tracker

- HQSmokeTests/testPages/data/export_data_page.py
- HQSmokeTests/testPages/reports/report_page.py
- HQSmokeTests/testPages/users/mobile_workers_page.py
Fix for profile locators and longer time for excel dashboard
Fix for profile locators and longer time for excel dashboard
[Jira link](https://dimagi-dev.atlassian.net/browse/QA-6444)
> QA-6444 fix for profile locators and longer time for excel dashboard

- LocustScripts/commcarehq-bed-avail.py
- LocustScripts/commcarehq-bed-track-non-ideal-case.py
- LocustScripts/commcarehq-bed-track.py
- LocustScripts/commcarehq-central-registry-search-and-admit.py
- LocustScripts/commcarehq-referrals-outgoing-referrals.py
- LocustScripts/commcarehq-referrals-search-for-beds.py
- LocustScripts/user/models.py
We are randomising user lists for case search tests. This change randomizes users for every test.
> Randomise users in every test

- .github/workflows/hq-smoke-tests.yml
- HQSmokeTests/testCases/test_01_others.py
- HQSmokeTests/testCases/test_06_data.py
- HQSmokeTests/testCases/test_10_p1_p2_defects.py
- HQSmokeTests/testPages/data/export_data_page.py
- HQSmokeTests/testPages/data/manage_forms_page.py
- HQSmokeTests/testPages/email/email_verification.py
- HQSmokeTests/userInputs/user_inputs.py
- common_utilities/hq_login/login_page.py
Added setups for executing the HQ Smoke Tests on India server and required steps
Added setups for executing the HQ Smoke Tests on India server and required steps
[Jira link](https://dimagi-dev.atlassian.net/browse/QA-5339)
> QA-5339 added settings to run scripts on india server

- .github/workflows/hq-smoke-tests.yml
- .github/workflows/request_api.yml
- HQSmokeTests/testCases/conftest.py
- HQSmokeTests/testPages/data/export_data_page.py
- HQSmokeTests/testPages/data/import_cases_page.py
- HQSmokeTests/userInputs/user_inputs.py
- RequestAPI/testCases/conftest.py
Added setups for executing the Request API Tests on India server and required steps
Added setups for executing the Request API Tests on India server and required steps
[Jira link](https://dimagi-dev.atlassian.net/browse/QA-5339)
> QA-5339 set up for api scripts on india server

- .github/workflows/hq-smoke-tests.yml
- .github/workflows/request_api.yml
Added new webhook url for India server reports publishing
Added new webhook url for India server reports publishing
[Jira link](https://dimagi-dev.atlassian.net/browse/QA-5339)
> QA-5339 updated india webhook urls in ymls

- Features/CaseSearch/test_cases/test_02_casesearch_configs.py
- Features/CaseSearch/test_pages/casesearch_page.py
- Features/SplitScreenCaseSearch/test_cases/test_02_casesearch_configs.py
- USH_Apps/CO_BHA/test_cases/test_01_admit_client_and_locks.py
- USH_Apps/CO_BHA/test_pages/bha_app_pages.py
- common_utilities/selenium/base_page.py
- common_utilities/selenium/webapps.py
Removed xfail tags from CS and SSCS tests, fixed BHA testcase step, updated webapps and base classes
Removed xfail tags from CS and SSCS tests, fixed BHA testcase step, updated webapps and base classes
[Jira link](https://dimagi-dev.atlassian.net/browse/QA-6520)
> QA-6520 removed xfail tags from CS and SSCS tests, fixed BHA test

- .github/workflows/bha-tests.yml
- Features/CaseSearch/test_pages/casesearch_page.py
- Features/SplitScreenCaseSearch/test_cases/test_02_casesearch_configs.py
- USH_Apps/CO_BHA/test_cases/conftest.py
- USH_Apps/CO_BHA/test_cases/test_01_admit_client_and_locks.py
- USH_Apps/CO_BHA/test_pages/bha_app_pages.py
- USH_Apps/CO_BHA/user_inputs/bha_user_inputs.py
- common_utilities/selenium/webapps.py
Changed domain parameters for BHA testsuite and changed steps for SSCS test
Changed domain parameters for BHA testsuite and changed steps for SSCS test
[Jira link](https://dimagi-dev.atlassian.net/browse/QA-6520)
> QA-6520 changed domain parameters for BHA testsuite and changed steps for SSCS test

- MobileTest/ccc_bulk_submission/README.md
- MobileTest/ccc_bulk_submission/main.py
- MobileTest/ccc_bulk_submission/requires.txt
Automated test for Bulk testing of form submissions added to repo
Automated test for Bulk testing of form submissions added to repo
[Jira link](https://dimagi-dev.atlassian.net/browse/QA-6273)
> QA 6273 Bulk testing of form submissions

- Features/CaseSearch/user_inputs/casesearch_user_inputs.py
- HQSmokeTests/testPages/android/android_screen.py
- USH_Apps/CO_BHA/test_pages/bha_app_pages.py
BHA locator and CS user input updated
BHA locator and CS user input updated
[Jira link](https://dimagi-dev.atlassian.net/browse/QA-6683)
> QA-6683 BHA locator and CS user input updated

- HQSmokeTests/testPages/messaging/messaging_page.py
- HQSmokeTests/testPages/reports/report_page.py
Exception handled for email and keyword scenarios for HQ Smoke tests
Exception handled for email and keyword scenarios for HQ Smoke tests
[Jira link](https://dimagi-dev.atlassian.net/browse/QA-6683)
> QA-6683 exception handled for email and keyword scenarios

- HQSmokeTests/testPages/applications/app_preview.py
- USH_Apps/CO_BHA/test_cases/test_01_admit_client_and_locks.py
- USH_Apps/CO_BHA/test_cases/test_02_discharge_client.py
- USH_Apps/CO_BHA/test_pages/bha_app_pages.py
- USH_Apps/CO_BHA/user_inputs/bha_user_inputs.py
BHA user input updated
BHA user input updated
[Jira link](https://dimagi-dev.atlassian.net/browse/QA-6683)
> QA-6683 BHA user input updated

- .github/workflows/bha-tests.yml
- Features/CaseSearch/test_pages/casesearch_page.py
- USH_Apps/CO_BHA/settings-sample.cfg
- USH_Apps/CO_BHA/test_cases/conftest.py
- USH_Apps/CO_BHA/test_cases/test_01_admit_client_and_locks.py
- USH_Apps/CO_BHA/test_pages/bha_app_pages.py
- USH_Apps/CO_BHA/user_inputs/bha_user_inputs.py
- common_utilities/selenium/webapps.py
BHA scripts updated with latest changes
BHA scripts updated with latest changes
[Jira link](https://dimagi-dev.atlassian.net/browse/QA-6761)
> QA-6761 BHA scripts updated with latest changes

- HQSmokeTests/testPages/android/android_screen.py
BS app url updated for the month
BS app url updated for the month
> QA-6864 BS app url updated for the month

- Features/CaseSearch/test_pages/casesearch_page.py
Added conditions on date format based on OS
Added conditions on date format based on OS
> QA-6864 Added conditions on date format based on OS

- HQSmokeTests/testPages/users/org_structure_page.py
Locator and condition updated for location cleanup
Locator and condition updated for location cleanup
> QA-6864 locator and condition updated for location cleanup

- Features/CaseSearch/test_pages/casesearch_page.py
- HQSmokeTests/testPages/users/mobile_workers_page.py
- common_utilities/selenium/webapps.py
Fix for CS testcase 28
Fix for CS testcase 28
> QA-6864 fix for CS testcase 28

- HQSmokeTests/testCases/test_09_messaging.py
- HQSmokeTests/testCases/test_10_p1_p2_defects.py
- HQSmokeTests/testPages/applications/application_page.py
- HQSmokeTests/testPages/home/home_page.py
- HQSmokeTests/testPages/messaging/messaging_page.py
- HQSmokeTests/testPages/project_settings/repeaters_page.py
Changes related to HQ Smoketest testcase 78
Changes related to HQ Smoketest testcase 78
> QA-6864 changes related to HQ Smoketest testcase 78

- Features/CaseSearch/test_cases/test_02_casesearch_configs.py
- Features/CaseSearch/test_cases/test_03_casesearch_misc.py
- common_utilities/selenium/webapps.py
CaseSearch fixes
CaseSearch fixes
[Jira link](https://dimagi-dev.atlassian.net/browse/QA-7048)
> QA-7048 CaseSearch fixes

- Features/CaseSearch/test_cases/test_02_casesearch_configs.py
- Features/CaseSearch/test_cases/test_03_casesearch_misc.py
- Features/CaseSearch/test_cases/test_04_casesearch_fuzzy_search.py
- Features/CaseSearch/test_cases/test_05_casesearch_inline_search.py
- Features/CaseSearch/test_cases/test_07_casesearch_data_registry.py
- Features/CaseSearch/test_pages/casesearch_page.py
- Features/MultiSelect/test_pages/multiselect_page.py
- Features/SplitScreenCaseSearch/test_cases/test_02_casesearch_configs.py
- Features/SplitScreenCaseSearch/test_cases/test_03_casesearch_misc.py
- Features/SplitScreenCaseSearch/test_cases/test_04_casesearch_fuzzy_search.py
- Features/SplitScreenCaseSearch/test_cases/test_05_casesearch_inline_search.py
- Features/SplitScreenCaseSearch/test_cases/test_07_casesearch_data_registry.py
- HQSmokeTests/testCases/test_09_messaging.py
- HQSmokeTests/testPages/messaging/messaging_page.py
- USH_Apps/CO_BHA/test_pages/bha_app_pages.py
Added proper assertion messages to all USH scripts.
Added proper assertion messages to all USH scripts.
[Jira link](https://dimagi-dev.atlassian.net/browse/QA-6613)
> QA-6613 added proper assertion messages to all USH scripts

- .github/workflows/bha-tests.yml
- .github/workflows/case-search-tests.yml
- .github/workflows/casesearch-split-screen-tests.yml
- .github/workflows/es-tests.yml
- .github/workflows/export-tests.yml
- .github/workflows/hq-smoke-tests.yml
- .github/workflows/multi-select-tests.yml
- .github/workflows/request_api.yml
- Features/MultiSelect/test_cases/test_01_multi_select.py
- HQSmokeTests/testPages/android/android_screen.py
- HQSmokeTests/testPages/data/data_dictionary_page.py
Updated BS app url, all ymls and MS log in user
Updated BS app url, all ymls and MS log in user
[Jira link](https://dimagi-dev.atlassian.net/browse/QA-7156)
> QA-7156 updated BS app url, all ymls and MS log in user

- .github/workflows/bha-tests.yml
- .github/workflows/case-search-tests.yml
- .github/workflows/casesearch-split-screen-tests.yml
- .github/workflows/hq-smoke-tests.yml
- .github/workflows/multi-select-tests.yml
- .github/workflows/request_api.yml
- HQSmokeTests/testPages/data/export_data_page.py
Added conditions on yml to skip staging deployments
Added conditions on yml to skip staging deployments
[Jira link](https://dimagi-dev.atlassian.net/browse/QA-7156)
> QA-7156 added conditions on yml to skip staging deployments

- ExportTests/testCases/test_02_integration_exports.py
- HQSmokeTests/testPages/data/export_data_page.py
- HQSmokeTests/testPages/data/import_cases_page.py
- P1P2Tests/testCases/test_04_integration_exports.py
Updated locators, steps for export data page
Updated locators, steps for export data page
[Jira link](https://dimagi-dev.atlassian.net/browse/QA-7156)
> QA-7156 updated locators, steps for export data page

- Formplayer/testCases/test_04_basic_test_forms_01.py
- Formplayer/testPages/basic_test_app/basic_test_app_preview.py
- Formplayer/testPages/basic_test_app/basic_test_web_apps.py
Fixed pagination assertions
Fixed pagination assertions
[Jira link](https://dimagi-dev.atlassian.net/browse/QA-90)
> QA-2857 fixed pagination assertions

- Formplayer/testPages/app_preview/login_as_app_preview_page.py
- Formplayer/testPages/basic_test_app/basic_test_app_preview.py
- Formplayer/testPages/basic_test_app/basic_test_web_apps.py
- Formplayer/testPages/webapps/login_as_page.py
Fixed basic text field locator
Fixed basic text field locator
[Jira link](https://dimagi-dev.atlassian.net/browse/QA-90)
> QA-2857 fixed basic text field locator

- Features/CaseSearch/test_cases/test_05_casesearch_inline_search.py
- Features/CaseSearch/test_pages/casesearch_page.py
- Features/SplitScreenCaseSearch/test_cases/test_05_casesearch_inline_search.py
- HQSmokeTests/testCases/test_06_data.py
- HQSmokeTests/testPages/data/import_cases_page.py
- common_utilities/selenium/webapps.py
Added fix for CS, HQ and new methods for data dictionary.
Added fix for CS, HQ and new methods for data dictionary.
[Jira link](https://dimagi-dev.atlassian.net/browse/QA-7889)
> QA-7889 fix for CS, HQ and new methods for data dictionary

- USH_Apps/CO_BHA/user_inputs/bha_user_inputs.py
Updated  app name for BHA
Updated app name for BHA
[Jira link](https://dimagi-dev.atlassian.net/browse/QA-7961)
> QA-7961 updated app name for BHA

- common_utilities/selenium/webapps.py
Fixed search function in webapps common utility
Fixed search function in webapps common utility
[Jira link](https://dimagi-dev.atlassian.net/browse/QA-7961)
> QA-7961 fixed search function in webapps common utility

- .github/workflows/data-dictionary-tests.yml
- .github/workflows/power-bi-tests.yml
- ElasticSearchTests/requires.txt
- ElasticSearchTests/testCases/conftest.py
- ExportTests/requires.txt
- ExportTests/testCases/conftest.py
- Features/CaseSearch/requires.txt
- Features/CaseSearch/test_cases/conftest.py
- Features/CaseSearch/test_pages/casesearch_page.py
- Features/Lookuptable/requires.txt
- Features/Lookuptable/testCases/conftest.py
- Features/MultiSelect/requires.txt
- Features/MultiSelect/test_cases/conftest.py
- Features/SplitScreenCaseSearch/requires.txt
- Features/SplitScreenCaseSearch/test_cases/conftest.py
- Formplayer/requires.txt
- Formplayer/testCases/conftest.py
- HQSmokeTests/requires.txt
- HQSmokeTests/testCases/conftest.py
- HQSmokeTests/testPages/android/android_screen_old.py
- HQSmokeTests/testPages/data/export_data_page.py
- P1P2Tests/requires.txt
- P1P2Tests/testCases/conftest.py
- RequestAPI/requirements.txt
- RequestAPI/testCases/conftest.py
- USH_Apps/CO_BHA/requires.txt
- USH_Apps/CO_BHA/test_cases/conftest.py
- USH_Apps/WeeklyBHACleanup/requires.txt
- USH_Apps/WeeklyBHACleanup/testCases/conftest.py
- common_utilities/selenium/webapps.py
This PR consists for a couple of new changes to the reports, apk uploads and regular script fixes
This PR consists for a couple of new changes to the reports, apk uploads and regular script fixes:
- Fix for 2 CS testcases
- Fix for the failing export testcases
- Added a function to auto upload commcare apk directly to Browserstack and collect the bs app url. This removed the monthly apk upload and then script updation task.
- Added Pie Chart as a Test Summary and a Graph to show reruns and failures
[Jira link](https://dimagi-dev.atlassian.net/browse/QA-8032)
> QA-8032 fix for CS testcase, added new setup to update bs app, added ymls for powerbi and data dictionary
